hnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('index.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^reservation/', include('reservation.urls')),
    url(r'^hospital/', include('hospital.urls')),
    url(r'^medical/', include('medical.urls')),
    url(r'^messaging/', include('messaging.urls')),
]

index/urls.py
from django.conf.urls import url
from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^patient/$', views.patient, name='patient'),
    url(r'^doctor/$', views.doctor, name='doctor'),
    url(r'^nurse/$', views.nurse, name='nurse'),
    url(r'^administrator/$', views.administrator, name='administrator'),
    url(r'^administrator/log/$', views.log, name='log'),
    url(r'^administrator/log/activity.log$', views.log, name='log'),
    url(r'^system_administrator/$', views.system_administrator, name='system_administrator'),
    url(r'^stephen$', views.stephen, name='stephen'),
]

reservation/urls.py
from django.conf.urls import url
from . import views

app_name = 'reservation'
urlpatterns = [
    url(r'^calendar/$', views.calendar, name='calendar_now'),
    url(r'^calendar/(?P<month>[0-9]{1,2})/(?P<year>[0-9]{4})/$', views.calendar, name='calendar'),
    url(r'^overview/$', views.overview, name='overview_today'),
    url(r'^overview/(?P<day>[0-9]{1,2})/(?P<month>[0-9]{1,2})/(?P<year>[0-9]{4})/$', views.overview, name='overview'),
    url(r'^create/$', views.create_appointment, name='create'),
    url(r'^create/done$', views.create_appointment_done, name='create_done'),
    url(r'^edit/(?P<appointment_id>[0-9]+)/$', views.edit_appointment, name='edit'),
    url(r'^cancel/(?P<appointment_id>[0-9]+)/$', views.cancel_appointment, name='cancel'),
    url(r'^weekview/(?P<day>[0-9]{1,2})/(?P<month>[0-9]{1,2})/(?P<year>[0-9]{4})/$', views.weekview, name='weekview'),
    url(r'^weekview/$', views.weekview, name='weekview_now'),
]

reservation/forms.py
import datetime

from django import forms
from django.db.models import Q
from reservation.models import Appointment
from datetime import date, timedelta


class BaseAppointmentForm(forms.ModelForm):
    """
    A form for the Appointment model that doesn't have either of the two participants fields.
    This form is not meant to be used directly, but rather subclassed.
    """

    def clean_date(self):
        date = self.cleaned_data['date']
        # Validate that the appointment isn't set to a date in the past.
        if date < datetime.datetime.now().date():
            raise forms.ValidationError('Cannot schedule appointment with a past date.')

        return date

    def clean(self):
        cleaned_data = super(BaseAppointmentForm, self).clean()

        # Validate that the provided appointment time does not conflict with another already existing appointment.

        # Make sure the data required for this validation process are valid,
        # otherwise don't even bother running this validation
        if 'date' not in cleaned_data or 'start_time' not in cleaned_data or 'end_time' not in cleaned_data:
            return cleaned_data

        # Get the valid date/time data
        date = cleaned_data['date']
        start_time = cleaned_data['start_time']
        end_time = cleaned_data['end_time']

        # Construct a query to find the appointments that have time conflicts with this one
        cancelled_q = Q(cancelled=False)
        date_q = Q(date=date)
        start_time_q = Q(start_time__lte=start_time) & Q(end_time__gte=start_time)
        end_time_q = Q(start_time__lte=end_time) & Q(start_time__gte=end_time)
        overall_time = Q(start_time__gte=start_time) & Q(start_time__lte=end_time)
        time_q = start_time_q | end_time_q | overall_time
        q = cancelled_q & date_q & time_q
        # Exclude this record from the results, since an appointment cannot conflict with itself.
        if self.instance.id is not None:
            q = ~Q(pk=self.instance.id) & q

        # Count the number of results returned from the query and determine if a conflict exists.
        if Appointment.objects.filter(q).count() > 0:
            raise forms.ValidationError('The time slot is not available, please try a different one.')

        return cleaned_data

    date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Appointment
        fields = ['title', 'date', 'start_time', 'end_time']


class AppointmentFormForPatient(BaseAppointmentForm):
    """
    An Appointment form for patient users.
    This form contains the 'doctor' field, which is the other participant of the appointment.
    The value for the 'patient' field should be supplied when saving.
    """

    def save(self, creator=None, commit=True):
        """
        Save the object with the given creator as the 'patient' participant.
        :param creator: The patient participant.
        """

        appointment = super(AppointmentFormForPatient, self).save(commit=False)

        if creator is not None:
            appointment.patient = creator.patient
            appointment.end_time = (datetime.datetime.combine(date.today(), appointment.start_time) +
                                    timedelta(minutes=30)).time()

            if commit:
                appointment.save()
        else:
            appointment.save()

        return appointment

    class Meta:
        model = Appointment
        fields = BaseAppointmentForm.Meta.fields + ['doctor']
        exclude = ('end_time',)


class AppointmentFormForDoctor(BaseAppointmentForm):
    """
    An appointment form for doctor users.
    This form contains the 'patient' field, which is the other participant of the appointment.
    The value for the 'doctor' field should be supplied when saving.
    """

    def save(self, creator=None, commit=True):
        """
        Save the object with the given creator as the 'doctor' participant.
        :param creator: The doctor participant.
        """

        if creator is not None:
            appointment = super(AppointmentFormForDoctor, self).save(commit=False)
            appointment.doctor = creator.doctor

            if commit:
                appointment.save()
        else:
            appointment = super(AppointmentFormForDoctor, self).save(commit)

        return appointment

    class Meta:
        model = Appointment
        fields = BaseAppointmentForm.Meta.fields + ['patient']

reservation/views.py
import datetime
import math

from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from reservation.models import Appointment, get_account_from_user
from reservation.forms import AppointmentFormForPatient, AppointmentFormForDoctor
from account.models import Patient, Doctor, Nurse, ProfileInformation, get_account_from_user
from hnet.logger import CreateLogEntry


@login_required
@permission_required('reservation.view_appointment')
@user_passes_test(lambda u: not u.is_superuser)
def calendar(request, month=datetime.date.today().month, year=datetime.date.today().year):
    """
    main calendar view. This is the monthview
    :param month: passed in month
    :param year: passed in year
    :return: monthview of the calendar
    """
    month = int(month)
    year = int(year)

    if not is_month_valid(month) or not is_year_valid(year):
        raise Http404()

    week_list = calculate_day(str(month), str(year))

    # forward and back arrow calculations
    if month == 1:
        prev_month = 12
        prev_year = year - 1
    else:
        prev_month = month - 1
        prev_year = year

    if month == 12:
        next_month = 1
        next_year = year + 1
    else:
        next_month = month + 1
        next_year = year

    month_name = datetime.date(1900, month, 1).strftime('%B')

    context = {'year': year, 'month': month, 'month_name': month_name,
               'prev_month': prev_month, 'prev_year': prev_year, 'next_month': next_month,
               'next_year': next_year, 'week_list': week_list}

    # grab all appointments for the select user
    profile_information = ProfileInformation.from_user(request.user)
    if profile_information is not None:
        account_type = profile_information.account_type
        if account_type == Patient.ACCOUNT_TYPE:
            appointments = Appointment.get_for_user_in_year_in_month(request.user.patient, year, month)
            if appointments is None:
                raise Http404()
            context['appointment_list'] = appointments
            return render(request, 'reservation/calendar.html', context)
        elif account_type == Doctor.ACCOUNT_TYPE:
            appointments = Appointment.get_for_user_in_year_in_month(request.user.doctor, year, month)
            if appointments is None:
                raise Http404()
            context['appointment_list'] = appointments
            return render(request, 'reservation/calendar.html', context)

    raise PermissionDenied()


@login_required()
@permission_required('reservation.view_appointment')
@user_passes_test(lambda u: not u.is_superuser)
def weekview(request, day=datetime.date.today().day, month=datetime.date.today().month,
             year=datetime.date.today().year):
    """
    weekview of the calendar. Displays the calendar and appointments
    for a given week instead of month
    :param request:
    :param day: start day of the week
    :param month: start month of the given week
    :param year: start year of the given week
    :return: weekview of the calendar with appointments
    """
    doctors = []
    person = "user"
    day = int(day)
    month = int(month)
    year = int(year)

    week_starting_date = datetime.date(day=day, month=month, year=year)
    weekday = week_starting_date.isoweekday()
    if weekday != 7:
        week_starting_date -= datetime.timedelta(days=weekday)
    week_ending_date = week_starting_date + datetime.timedelta(days=6)

    # if nurse, get selected doctors to show, otherwise show your own appointments
    doctor_list = None
    profile_information = ProfileInformation.from_user(request.user)
    account_type = profile_information.account_type
    if account_type == Nurse.ACCOUNT_TYPE:
        nurse = get_account_from_user(request.user)
        hospital = nurse.hospital
        person = "nurse"
        doctors = Doctor.objects.all().filter(hospital=hospital)
        if request.method == "POST":
            doctor_list = [parse_int(x) for x in request.POST.getlist("doctor_list")]
            appointments = Appointment.objects.filter(cancelled=False).filter(doctor_id__in=doctor_list)
        else:
            appointments = Appointment.objects.filter(cancelled=False).filter(doctor__hospital=hospital)
    else:
        appointments = Appointment.get_for_user_in_week_starting_at_date(request.user, week_starting_date)

    week = get_week(week_starting_date, week_ending_date)
    last_week = week_starting_date - datetime.timedelta(days=1)
    next_week = week_ending_date + datetime.timedelta(days=1)
    # 'start_date' and 'end_date' are `datetime.date` objects representing the dates at the start and end of the week.
    context = {'appointment_list': appointments, 'week': week, 'start_day': week_starting_date,
               'end_day': week_ending_date, 'next_week': next_week, 'last_week': last_week, 'person': person,
               'doctors': doctors, 'selected_doctor_list': doctor_list}

    return render(request, 'reservation/weekview.html', context)


@login_required
@permission_required('reservation.view_appointment')
@user_passes_test(lambda u: not u.is_superuser)
def overview(request, day=None, month=None, year=None):
    """
    main overview for a selected day.
    Tells you all the appointments for that day
    :param request: requested page
    :param day: current day that was selected
    :param month: month of the day that was selected
    :param year: year of the day that was selected
    :return: page with all the appointments for a given day
    """
    if day is None or month is None or year is None:
        date = datetime.date.today()
    else:
        try:
            date = datetime.date(int(year), int(month), int(day))
        except ValueError:
            raise Http404()

    month_name = datetime.date(1900, date.month, 1).strftime('%B')

    context = {'month_name': month_name, 'date': date,
               'can_cancel': request.user.has_perm('reservation.cancel_appointment')}

    profile_information = ProfileInformation.from_user(request.user)
    if profile_information is not None:
        account_type = profile_information.account_type
        if account_type == Patient.ACCOUNT_TYPE:
            appointments = Appointment.get_for_user_in_date(request.user.patient, date)
            context['appointment_list'] = appointments
            return render(request, 'reservation/overview.html', context)
        elif account_type == Doctor.ACCOUNT_TYPE:
            appointments = Appointment.get_for_user_in_date(request.user.doctor, date)
            context['appointment_list'] = appointments
            return render(request, 'reservation/overview.html', context)
        elif account_type == Nurse.ACCOUNT_TYPE:
            hospital = request.user.nurse.hospital
            # filter all cancelled and appointments that are not for a given hospital for the Nurse
            appointments = Appointment.objects.filter(cancelled=False).filter(date=date).filter(doctor__hospital=hospital)
            context['appointment_list'] = appointments
            return render(request, 'reservation/overview_nurse.html', context)

    raise PermissionDenied()


@login_required
@permission_required('reservation.add_appointment')
@user_passes_test(lambda u: not u.is_superuser)
def create_appointment(request):
    """
    Used to create an appointment. Sys admins/admins/nurses are
    not able to view this page
    :param request: page requested
    :return: none
    """
    profile_information = ProfileInformation.from_user(request.user)
    account_type = profile_information.account_type
    if account_type == Patient.ACCOUNT_TYPE:
        form_type = AppointmentFormForPatient
    elif account_type == Doctor.ACCOUNT_TYPE:
        # doctors have different form than patient
        form_type = AppointmentFormForDoctor
    else:
        raise PermissionDenied()

    if request.method == 'POST':
        form = form_type(request.POST)
        if form.is_valid():
            CreateLogEntry(request.user.username, "Appointment created.")
            form.save(request.user)
            return redirect(reverse('reservation:create_done'))
    else:
        form = form_type()

    return render(request, 'reservation/appointment/create.html', {'form': form})


@login_required
@permission_required('reservation.add_appointment')
def create_appointment_done(request):
    """
    Used to notify user that an appointment has been created
    :param request: requested page
    :return: none
    """
    return render(request, 'reservation/appointment/create_done.html')


@login_required
@permission_required('reservation.change_appointment')
def edit_appointment(request, appointment_id):
    """
    Used to edit a selected appointment
    to change the time or reason etc.
    :param request: page requested by user
    :param appointment_id: id of the appointment
    :return: none
    """
    appointment = get_object_or_404(Appointment, pk=appointment_id)

    if not appointment.accessible_by_user(request.user):
        raise PermissionDenied()

    if ProfileInformation.from_user(request.user).account_type == Doctor.ACCOUNT_TYPE:
        if request.method == 'POST':
            form = AppointmentFormForDoctor(request.POST, instance=appointment)
            if form.is_valid():
                CreateLogEntry(request.user.username, "Appointment edited.")
                form.save()
                return render(request, 'reservation/appointment/edit.html',
                              {'form': form, 'message': 'All changes saved.'})
        else:
            form = AppointmentFormForDoctor(instance=appointment)
    else:
        if request.method == 'POST':
            form = AppointmentFormForPatient(request.POST, instance=appointment)

reservation/templates/reservation/calendar.html
{% extends 'index/base.html' %}
{% block title %}Appointment Calendar{% endblock %}
{% block header %}Appointment Calendar{% endblock %}
{% block content %}
<br/>

<div class="container" style="margin-top:74px;">

    <div class="month" style="text-align: center;">
        <div class="row">
            <div class="col-md-1 col-md-push-10"><a href="#" style="color:white;text-decoration:none;">
                <i class="fa fa-calendar" aria-hidden="true"></i> Monthview</a></div>
            <div class="col-md-1 col-md-push-10">
                <a href="{% url 'reservation:weekview_now' %}" style="color:white;text-decoration:none;">
                    <i class="fa fa-calendar-minus-o" aria-hidden="true"></i> Weekview</a></div>

        </div>
        <table>
            <tr>
                <td class="prev"><a href="{% url 'reservation:calendar' prev_month prev_year %}"
                                    style="text-decoration: none;color: white;">&#10094;</a></td>
                <td class="monthhead">{{ month_name }} {{ year}} {{ last_month }}</td>
                <td class="next"><a href="{% url 'reservation:calendar' next_month next_year %}"
                                    style="text-decoration: none;color: white;">&#10095;</a></td>
            </tr>
        </table>
        <a href="{% url 'reservation:overview_today' %}" style="color:white;text-decoration:underline;">Today</a>
    </div>
    <ul class="weekdays">
        <li>Sunday</li>
        <li>Monday</li>
        <li>Tuesday</li>
        <li>Wednesday</li>
        <li>Thursday</li>
        <li>Friday</li>
        <li>Saturday</li>
    </ul>

    <div class="calendar">

        <table class="calbox">

            {% for week in week_list %}
            <tr>
                {% for day in week %}
                {% if day == "none" %}
                <td style="background-color:#1988B5; border:none;"><p style="color: #1988B5">{{ day }}</p>

                </td>
                {% else %}
                <td style="background-color:#ddd">{{ day }}
                    <a href="{% url 'reservation:overview' day month year %}" class="infobox"
                       style="text-decoration:none;color:black;display:block;">
                        <ul style="background-color:#ddd; padding-left:15px;">
                            {% for appointment in appointment_list %}
                            {% if appointment.date.day == day %}
                            {% if appointment.date.month == month %}
                            <li>{{ appointment.title }}: <p style="font-size:10px;">{{ appointment.start_time }}
                                -{{appointment.end_time }}</p></li>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </a>
                </td>

                {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}

        </table>
    </div>
</div>

{% endblock %}

reservation/templates/reservation/detail.html
<h1>{{ appointment.title }}</h1>


<h4><a href="{% url 'reservation:edit' item.id %}">Appointment Name</a></h4>
<p>Patient Name: {{ item.patient }}<br/>
    Doctor Name: {{ item.doctor }}<br/>
    Time: {{ item.date_time }}</p>


<button><a href="{% url 'reservation:create' %}" style="text-decoration:none">Create</a></button>

reservation/templates/reservation/overview.html
{% extends 'index/base.html' %}
{% block title %}Appointment Overview{% endblock %}
{% block header %}Appointments for {{ month_name }} {{ date.day }}, {{ date.year }}{% endblock %}
{% block content %}

<div class="container" style="margin-top:75px;">
    <div class="well">
        {% for appointment in appointment_list %}
        <h4>{{ appointment.title }}</h4>
        <p>Patient Name: {{ appointment.patient }}<br/>
            Doctor Name: {{ appointment.doctor }}<br/>
            Room: {{ appointment.location }}<br/>
            Time: {{ appointment.start_time }} - {{ appointment.end_time }}</p>
        <a href="{% url 'reservation:edit' appointment.id %}" class="btn btn-default btn-md inactive"
           role="button">Edit Appointment</a>
        {% if can_cancel %}
        <a href="{% url 'reservation:cancel' appointment.id %}" class="btn btn-default btn-md inactive"
           role="button">Cancel Appointment</a>
        <br />
        {% endif %}
        {% empty %}

        <p style="text-align:center;">You have no appointments. Click 'Create' to schedule an appointment.</p>
        <br />
        {% endfor %}
        <div class="row">
            <div class="col-md-5 col-md-offset-4">
                <button class="button"><a href="{% url 'reservation:create' %}">Create</a></button>
                <button class="button">
                    <a href="{% url 'reservation:calendar' date.month date.year %}">Calendar</a>
                </button>
                <button class="button"><a href="{% url 'index:index' %}">Dashboard</a></button>
            </div>
            <br/>
        </div>
    </div>
    {% endblock %}

reservation/templates/reservation/overview_nurse.html
{% extends 'index/base.html' %}
{% block title %}Appointment Overview{% endblock %}
{% block header %}Appointments for {{ month_name }} {{ date.day }}, {{ date.year }}{% endblock %}
{% block content %}

    <div class="container" style="margin-top:75px;">
        <div class="well">
            {% for appointment in appointment_list %}
                <h4>{{ appointment.title }}</h4>
                <p>Patient Name: {{ appointment.patient }}<br/>
                    Doctor Name: {{ appointment.doctor }}<br/>
                    Room: {{ appointment.location }}<br/>
                    Time: {{ appointment.start_time }} - {{ appointment.end_time }}</p>
            {% empty %}

                <p style="text-align:center;">There is no appointment on this date.</p>
                <br/>
            {% endfor %}
            <div class="row">
                <div class="col-md-5 col-md-offset-4">
                    <button class="button">
                        <a href="{% url 'reservation:weekview' date.day date.month date.year %}">Calendar</a>
                    </button>
                    <button class="button"><a href="{% url 'index:index' %}">Dashboard</a></button>
                </div>
                <br/>
            </div>
        </div>
    </div>
{% endblock %}

reservation/templates/reservation/weekview.html
{% extends 'index/base.html' %}
{% block title %}Appointment Calendar{% endblock %}
{% block header %}Weekview Calendar{% endblock %}

{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <div class="container" style="margin-top:74px">
        <div class="month" style="text-align: center; margin-left:-14px; margin-right:-14px;">
            <div class="row">
                {% if person == "user" %}
                    <div class="col-md-1 col-md-push-10">
                        <a href="{% url 'reservation:calendar_now' %}" style="color:white;text-decoration:none;">
                            <i class="fa fa-calendar" aria-hidden="true"></i> Monthview</a></div>
                    <div class="col-md-1 col-md-push-10"><a href="#" style="color:white;text-decoration:none;">
                        <i class="fa fa-calendar-minus-o" aria-hidden="true"></i> Weekview</a></div>
                {% endif %}
            </div>
            <table>
                <tr>
                    <td class="prev"><a
                            href="{% url 'reservation:weekview' last_week.day last_week.month last_week.year %}"
                            style="text-decoration: none;color: white;">&#10094;</a></td>
                    <td class="monthhead" style="font-size:">{{ start_day }} - {{ end_day }}</td>
                    <td class="next"><a
                            href="{% url 'reservation:weekview' next_week.day next_week.month next_week.year %}"
                            style="text-decoration: none;color: white;">&#10095;</a></td>
                </tr>
            </table>
            <a href="{% url 'reservation:overview_today' %}" style="color:white;">Today</a>
        </div>
        <div class="row seven-cols">
            <div class="col-md-1 dayview weekblock">Sunday</div>
            <div class="col-md-1 dayview weekblock">Monday</div>
            <div class="col-md-1 dayview weekblock">Tuesday</div>
            <div class="col-md-1 dayview weekblock">Wednesday</div>
            <div class="col-md-1 dayview weekblock">Thursday</div>
            <div class="col-md-1 dayview weekblock">Friday</div>
            <div class="col-md-1 dayview weekblock">Saturday</div>
        </div>

        <div class="col-xs-12" style="height:50px;"></div>

        <div class="row seven-cols">
            {% for day in week %}
                <div class="col-md-1 dayblock" style="background-color:#ddd;">{{ day.day }}
                    <a href="{% url 'reservation:overview' day.day day.month day.year %}" class="infobox"
                       style="text-decoration:none;color:black;display:block;">
                        <ul style="background-color:#ddd; padding-left:0px;">
                            {% for appointment in appointment_list %}
                                {% if appointment.date.day == day.day %}
                                    {% if appointment.date.month == day.month %}
                                        <li>{{ appointment.title }}: <p
                                                style="font-size:10px;">{{ appointment.start_time }}
                                            -{{ appointment.end_time }}</p></li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </a>
                </div>
            {% endfor %}
        </div>


        {% if person == "nurse" %}
            <div class="panel-group" style="margin-top:20px;">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse1">Click to open Doctor list</a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse">
                        <ul class="list-group">
                            <form action="" method="post">
                                {% csrf_token %}
                                {% for doctor in doctors %}
                                    <li class="list-group-item">
                                        {% if doctor.id in selected_doctor_list %}
                                            <input type="checkbox" name="doctor_list" value="{{ doctor.id }}" checked>
                                        {% else %}
                                            <input type="checkbox" name="doctor_list" value="{{ doctor.id }}">
                                        {% endif %}
                                        Dr. {{ doctor.user.first_name }} {{ doctor.user.last_name }}
                                    </li>
                                {% endfor %}
                                <li class="list-group-item"><input type="submit" value="Save" class="button-sm"/></li>
                            </form>
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>


{% endblock %}