account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'account'
urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'account/common/login.html', 'authentication_form': forms.UserAuthenticationForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'account/common/logout.html'}, name='logout'),
    url(r'^patient/register/$', views.register_patient, name='register_patient'),
    url(r'^administrator/create/$', views.create_administrator, name='create_administrator'),
    url(r'^doctor/create/$', views.register_doctor, name='create_doctor'),
    url(r'^nurse/create/$', views.create_nurse, name='create_nurse'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^add/$', views.add_account, name='add_account'),
]

hnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('index.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^reservation/', include('reservation.urls')),
    url(r'^hospital/', include('hospital.urls')),
    url(r'^medical/', include('medical.urls')),
    url(r'^messaging/', include('messaging.urls')),
]

medical/urls.py
from django.conf.urls import url
from . import views

app_name = 'medical'
urlpatterns = [
    url(r'^drug/$', views.list_drug, name='list_drug'),
    url(r'^drug/add/$', views.add_drug, name='add_drug'),
    url(r'^drug/remove/(?P<drug_id>[0-9]+)/$', views.remove_drug, name='remove_drug'),
    url(r'^drug/update/(?P<drug_id>[0-9]+)/$', views.update_drug, name='update_drug'),
    url(r'^patient/$', views.view_patients, name='view_patients'),
    url(r'^patient_admin/$', views.view_patients_admin, name='view_patients_admin'),
    url(r'^patient/(?P<patient_id>[0-9]+)/$', views.view_medical_information, name='view_medical_information'),
    url(r'^diagnosis/create/(?P<patient_id>[0-9]+)/$', views.create_diagnosis, name='create_diagnosis'),
    url(r'^diagnosis/update/(?P<diagnosis_id>[0-9]+)/$', views.update_diagnosis, name='update_diagnosis'),
    url(r'^diagnosis/archive/(?P<diagnosis_id>[0-9]+)/$', views.archive_diagnosis, name='archive_diagnosis'),
    url(r'^prescriptions/(?P<patient_id>[0-9]+)/$', views.view_prescriptions, name='view_prescriptions'),
    url(r'^prescriptions/add/(?P<diagnosis_id>[0-9]+)/$', views.add_prescription, name='add_prescriptions'),
    url(r'^prescriptions/edit/(?P<prescription_id>[0-9]+)/$', views.edit_prescription, name='edit_prescriptions'),
    url(r'^prescriptions/remove/(?P<prescription_id>[0-9]+)/$', views.remove_prescription, name='remove_prescription'),
    url(r'^test/request/(?P<diagnosis_id>[0-9]+)/$', views.request_test, name='request_test'),
    url(r'^test/upload/(?P<test_id>[0-9]+)/$', views.upload_test_result, name='upload_test_result'),
    url(r'^test/test_view/$', views.test_view, name='test_view'),
    url(r'^test/release/(?P<test_id>[0-9]+)/$', views.release_test_result, name='release_test_result'),
    url(r'^test/test_detail/(?P<test_id>[0-9]+)/$', views.test_detail, name='test_detail'),
    url(r'^download_info/$', views.export_information, name='export_information'),
    url(r'^medical_info/$', views.medical_view_options, name='medical_info'),
    url(r'^medical_overview/$', views.medical_overview, name='medical_overview')
]

medical/forms.py
from django import forms
from .models import Drug, Diagnosis, Test, Prescription
from account.models import Patient


class DrugForm(forms.ModelForm):
    """
    A form for obtaining information related to a drug.
    Can be used for adding new drugs as well as editing existing drugs.
    """

    class Meta:
        model = Drug
        fields = ['name', 'description']


class DiagnosisForm(forms.ModelForm):
    def save_for_patient(self, patient):
        diagnosis = self.save(commit=False)

        diagnosis.patient = patient

        treatment_session = patient.get_current_treatment_session()
        if treatment_session:
            diagnosis.treatment_session = treatment_session
        else:
            pass

        diagnosis.save()

        return diagnosis

    class Meta:
        model = Diagnosis
        fields = ['summary']


class TestForm(forms.ModelForm):
    """
    A form for obtaining information for a medical test.
    """

    def save_for_diagnosis(self, doctor, diagnosis):
        test = self.save(commit=False)
        test.doctor = doctor
        test.diagnosis = diagnosis
        test.save()

        return test

    class Meta:
        model = Test
        fields = ['description']


class TestResultsForm(forms.ModelForm):
    """
    A form for obtaining test results in text form.
    """

    def uploadfile(self, file, commit=True):
        test = super(TestResultsForm, self).save(commit=commit)
        test.file = file
        test.uploaded = True
        test.save()

    def save(self, commit=True):
        test = super(TestResultsForm, self).save(commit=commit)
        test.uploaded = True
        test.save()

        return test

    class Meta:
        model = Test
        fields = ['results', 'file']


class PrescriptionForm(forms.ModelForm):
    def save_to_diagnosis_by_doctor(self, diagnosis, doctor, commit=True):
        prescription = super(PrescriptionForm, self).save(commit=False)
        prescription.diagnosis = diagnosis
        prescription.doctor = doctor

        if commit:
            prescription.save()

        return prescription

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if amount is not None and amount <= 0:
            raise forms.ValidationError('Cannot prescribe 0 or less units of drugs.')

        return amount

    def clean_cycle(self):
        cycle = self.cleaned_data.get('cycle')
        if cycle is not None and cycle <= 0:
            raise forms.ValidationError('Invalid value. Cycle duration must be greater than 0.')

        return cycle

    def clean_repeats(self):
        repeats = self.cleaned_data.get('repeats')
        if repeats is not None and repeats <= 0:
            raise forms.ValidationError('Invalid value. Repeat count must be greater than 0.')

        return repeats

    def clean(self):
        cleaned_data = super(PrescriptionForm, self).clean()
        repeats = self.cleaned_data.get('repeats')
        cycle = self.cleaned_data.get('cycle')

        if (repeats is None) != (cycle is None):
            raise forms.ValidationError('Cycle and repeats must be given at the same time.')

        return cleaned_data

    class Meta:
        model = Prescription
        fields = ['drug', 'instruction', 'amount', 'cycle', 'repeats']

medical/views.py
from urllib.parse import urlencode
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from hospital.models import TreatmentSession
from account.models import Patient, Nurse, get_account_from_user
from .models import Drug, Diagnosis, Test, Prescription
from .forms import DrugForm, DiagnosisForm, TestForm, TestResultsForm, PrescriptionForm
from hnet.logger import CreateLogEntry
import os
from django.conf import settings
from django.http import HttpResponse


@login_required
@permission_required('medical.view_drug')
@user_passes_test(lambda u: not u.is_superuser)
def list_drug(request):
    """ Get the list of the drugs"""
    drug_list = Drug.objects.filter(active=True).order_by('name')

    return render(request, 'medical/drug/list.html', {'drug_list': drug_list})


@login_required
@permission_required('medical.add_drug')
@user_passes_test(lambda u: not u.is_superuser)
def add_drug(request):
    """
    Only administrators are able to add in new
    drugs for a hospital
    """
    if request.method == 'POST':
        form = DrugForm(request.POST)
        if form.is_valid():
            form.save()
            CreateLogEntry(request.user.username, "Added new drug.")
            return render(request, 'medical/drug/add_done.html')
    else:
        form = DrugForm()

    return render(request, 'medical/drug/add.html', {'form': form})


@login_required
@permission_required('medical.view_prescription')
@user_passes_test(lambda u: not u.is_superuser)
def view_prescriptions(request, patient_id):
    """
    patients and doctors and nurses are able to view prescriptions
    for a given patient
    :param patient_id: id of the patient that is being accesed
    :return: list of prescriptions for a patient
    """
    patient = get_object_or_404(Patient, pk=patient_id)
    prescriptions = Prescription.objects.all()
    list_prescription = []
    for prescription in prescriptions:
        if prescription.active():
            if prescription.diagnosis.patient == patient:
                list_prescription.append(prescription)
    context = {'prescription_list': list_prescription, 'patient': patient}
    return render(request, 'patient/patient_overview.html', context)


@permission_required('medical.add_prescription')
@user_passes_test(lambda u: not u.is_superuser)
def add_prescription(request, diagnosis_id):
    """Doctors are able to prescribe for a patient after diagnosing"""
    diagnosis = get_object_or_404(Diagnosis, pk=diagnosis_id)

    if request.method == 'POST':
        form = PrescriptionForm(request.POST)
        if form.is_valid():
            form.save_to_diagnosis_by_doctor(diagnosis, request.user.doctor)
            CreateLogEntry(request.user.username, "Added prescription.")
            return render(request, 'medical/prescriptions/add_done.html', {'diagnosis_id': diagnosis_id})
    else:
        form = PrescriptionForm()

    return render(request, 'medical/prescriptions/add.html', {'form': form, 'diagnosis_id': diagnosis_id})


@permission_required('medical.change_prescription')
@user_passes_test(lambda u: not u.is_superuser)
def edit_prescription(request, prescription_id):
    """Doctors can edit a prescription to change amounts or frequency of use"""
    prescription = get_object_or_404(Prescription, pk=prescription_id)

    doctor = request.user.doctor
    if prescription.doctor != doctor:
        """Doctors are only able to edit prescriptions they made"""
        raise PermissionDenied('Cannot edit prescriptions created by another doctor.')

    if request.method == 'POST':
        form = PrescriptionForm(request.POST, instance=prescription)
        if form.is_valid():
            form.save()
            CreateLogEntry(request.user.username, "Edited prescription.")
            return render(request, 'medical/prescriptions/edit.html', {'form': form, 'message': 'All changes saved.'})
    else:
        form = PrescriptionForm(instance=prescription)

    return render(request, 'medical/prescriptions/edit.html', {'form': form})


@permission_required('medical.delete_prescription')
@user_passes_test(lambda u: not u.is_superuser)
def remove_prescription(request, prescription_id):
    """
    Doctors are able to remove a prescription for a patient but only
    if they created it themselves
    """
    prescription = get_object_or_404(Prescription, pk=prescription_id)

    doctor = request.user.doctor
    if prescription.doctor != doctor:
        raise PermissionDenied('Cannot delete prescriptions created by another doctor.')

    if request.method == 'POST':
        diagnosis_id = prescription.diagnosis.id
        prescription.delete()
        CreateLogEntry(request.user.username, "Prescription deleted.")
        return render(request, 'medical/prescriptions/remove_done.html', {'diagnosis_id': diagnosis_id})

    return render(request, 'medical/prescriptions/remove.html', {'prescription': prescription})


@login_required
@permission_required('account.view_patients')
@user_passes_test(lambda u: not u.is_superuser)
def view_patients(request):
    """
    Nurses and Doctors are able to view the patients in their hospital
    """
    account = get_account_from_user(request.user)
    hospital = account.hospital

    patients = Patient.objects.all()
    if request.user.profile_information.account_type == Nurse.ACCOUNT_TYPE:
        patients = [p for p in patients if p.get_admitted_hospital() == hospital or p.preferred_hospital == hospital]

    context = {'patient_list': patients, 'hospital': hospital}

    return render(request, 'patient/view_patients.html', context)


@login_required
@permission_required('hospital.transfer_patient_any_hospital')
@user_passes_test(lambda u: not u.is_superuser)
def view_patients_admin(request):
    """
    Administrators are able to transfer patients to other hospitals
    so they must also be able to see patients for any hospital
    """
    admin = get_account_from_user(request.user)
    hospital = admin.hospital
    list_patients = []
    patients = Patient.objects.all()
    for patient in patients:
        session = patient.get_current_treatment_session()
        if session:
            if session.treating_hospital == hospital:
                list_patients.append(patient)

    context = {'patient_list': list_patients, 'hospital': hospital}

    return render(request, 'patient/view_patients_admin.html', context)


@permission_required('medical.remove_drug')
@user_passes_test(lambda u: not u.is_superuser)
def remove_drug(request, drug_id):
    """
    Administrators can remove drugs from the
    drug list at the hospitals
    """
    drug = get_object_or_404(Drug, pk=drug_id)

    if not drug.active:
        return render(request, 'medical/drug/already_removed.html')

    if request.method == 'POST':
        drug.active = False
        drug.save()
        CreateLogEntry(request.user.username, "Drug removed.")
        return render(request, 'medical/drug/remove_done.html')
    else:
        return render(request, 'medical/drug/remove.html', {'drug': drug})


@permission_required('medical.change_drug')
@user_passes_test(lambda u: not u.is_superuser)
def update_drug(request, drug_id):
    """
    Administrators are able to update the description
    or name of a specific drug in a list
    """
    drug = get_object_or_404(Drug, pk=drug_id)
    if not drug.active:
        raise Http404()

    if request.method == 'POST':
        form = DrugForm(request.POST, instance=drug)
        if form.is_valid():
            form.save()
            CreateLogEntry(request.user.username, "Removed drug.")
            return render(request, 'medical/drug/update.html', {'form': form, 'message': 'All changes saved.'})
    else:
        form = DrugForm(instance=drug)

    return render(request, 'medical/drug/update.html', {'form': form})


@permission_required('medical.view_diagnosis')
@permission_required('hospital.view_treatmentsession')
def view_medical_information(request, patient_id):
    """
    Displays the medical information for a requested patient
    Only nurses and doctors have this permission, as do patients
    to view their own information
    """
    patient = get_object_or_404(Patient, pk=patient_id)

    medical_information = list(Diagnosis.objects.filter(patient=patient).filter(treatment_session=None))
    medical_information.extend(TreatmentSession.objects.filter(patient=patient))

    medical_information.sort(
        reverse=True,
        key=lambda item: item.creation_timestamp if isinstance(item, Diagnosis) else item.admission_timestamp
    )

    can_transfer = False
    if patient.get_current_treatment_session() is not None:
        if request.user.has_perm("hospital.transfer_patient_receiving_hospital"):
            can_transfer = get_account_from_user(request.user).hospital != \
                           patient.get_current_treatment_session().treating_hospital

    return render(request, 'medical/patient/medical_information.html', {
        'medical_information': medical_information, 'patient': patient,
        'user_has_edit_permission': request.user.has_perm('medical.change_diagnosis'),
        'user_has_add_permission': request.user.has_perm('medical.add_diagnosis'),
        'can_discharge': request.user.has_perm('hospital.discharge_patient'),
        'can_transfer': can_transfer,
    })


@login_required
@permission_required('medical.add_diagnosis')
def create_diagnosis(request, patient_id):
    """Doctors are able to create a diagnosis for a patient"""
    patient = get_object_or_404(Patient, pk=patient_id)

    if request.method == 'POST':
        form = DiagnosisForm(request.POST)
        if form.is_valid():
            diagnosis = form.save_for_patient(patient)

medical/templates/medical/drug/add.html
{% extends 'index/base.html' %}
{% block title %}Add Drug{% endblock %}
{% block header %}Add Drug{% endblock %}
{% block content %}
    <div class="maincontent">
        <div class="whitebox_small">
            <form method="post" action="{% url 'medical:add_drug' %}">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <div class="parentbutton">
                    <div class="leftbutton">
                        <input type="submit" value="Create" class="button"/>
                    </div>
                    <div class="rightbutton">
                        <a href="#" onclick="window.history.back(); return false;">
                            <button class="button">Back</button>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

medical/templates/medical/drug/add_done.html
{% extends 'index/base.html' %}
{% block title %}Drug Added{% endblock %}
{% block header %}Drug Added Confirmation{% endblock %}

{% block content %}

    <div class="maincontent">
        <div class="whitebox_small">

            <h2>Drug added</h2>

            <div class="parentbutton">
                <div class="leftbutton">
                    <a href="{% url 'medical:add_drug' %}" class="button">Add another drug</a>
                </div>
                <div class="rightbutton">
                    <a href="{% url 'medical:list_drug' %}" class="button">Return to drug list</a>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

medical/templates/medical/drug/already_removed.html
{% extends 'index/base.html' %}
{% block title %}Remove Drug{% endblock %}
{% block header %}Remove Drug Page{% endblock %}
{% block content %}

<div class="maincontent">
    <div class="whitebox">
        <p>Drug was already removed.</p>
    </div>
</div>

{% endblock %}

medical/templates/medical/drug/list.html
{% extends 'index/base.html' %}
{% block title %}Drugs{% endblock %}
{% block header %}Drug List Page{% endblock %}
{% block calendar %}Calendar <span class="caret"></span>{% endblock %}
{% block profile %}Profile <span class="caret"></span>{% endblock %}
{% block login %}
    <li><a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
{% endblock %}

{% block content %}
    <div class="maincontent">
        <div class="whitebox_small">

            <h2>Available Drugs</h2>

            <table class="table table-condensed">
                <tbody>

                {% for drug in drug_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'medical:update_drug' drug.id %}" style="font-size: 14pt;">{{ drug }}</a></td>
                        <td><a href="{% url 'medical:remove_drug' drug.id %}" style="margin-left: 24px;"
                               class="btn btn-danger btn-xs">Remove</a></td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

            <a href="{% url 'medical:add_drug' %}" class="button">Add New Drug</a>

        </div>
    </div>
{% endblock %}

medical/templates/medical/drug/remove.html
{% extends 'index/base.html' %}
{% block title %}Remove Drug{% endblock %}
{% block header %}Remove Drug Page{% endblock %}
{% block content %}

<div class="maincontent">
    <div class="whitebox">
        <p>Are you sure you want to remove this drug?</p>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="post" value="yes"/>
            <input type="submit" value="Yes, Remove" class="btn btn-default btn-lg inactive"/>
            <a href="#" onclick="window.history.back(); return false;" class="btn btn-default btn-lg inactive"
                       role="button">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

medical/templates/medical/drug/remove_done.html
{% extends 'index/base.html' %}
{% block title %}Remove Drug{% endblock %}
{% block header %}Remove Drug Page{% endblock %}
{% block content %}
<script>
    function redirect(){
       window.location.href = "{% url 'medical:add_drug' %}";
    }

    setTimeout(redirect, 3000); //3000 is equivalent to 3 seconds
</script>

<div class="maincontent">
    <div class="whitebox" style="text-align:center;">
        <p>Drug successfully removed. If you are not redirected in 3 seconds,
            <a href="{% url 'medical:list_drug' %}">click here</a> to return to drug list.</p>
    </div>
</div>

{% endblock %}

medical/templates/medical/drug/update.html
{% extends 'index/base.html' %}
{% block title %}Edit Drug{% endblock %}
{% block header %}Edit Drug{% endblock %}

{% block content %}
    <div class="maincontent">
        <div class="whitebox">
            <form method="post" action="{% url 'medical:update_drug' form.instance.id %}">
                {% if message %}
                    <p style="text-align: center;">{{ message }}</p>
                {% endif %}
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>

                <div class="parentbutton">
                    <div class="leftbutton">
                        <input type="submit" value="Save" class="btn btn-default btn-lg inactive"/>
                    </div>
                    <div class="rightbutton">
                        <a href="{% url 'medical:list_drug' %}" class="btn btn-default btn-lg inactive" role="button">
                            Back to list
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}