hnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('index.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^reservation/', include('reservation.urls')),
    url(r'^hospital/', include('hospital.urls')),
    url(r'^medical/', include('medical.urls')),
    url(r'^messaging/', include('messaging.urls')),
]

medical/urls.py
from django.conf.urls import url
from . import views

app_name = 'medical'
urlpatterns = [
    url(r'^drug/$', views.list_drug, name='list_drug'),
    url(r'^drug/add/$', views.add_drug, name='add_drug'),
    url(r'^drug/remove/(?P<drug_id>[0-9]+)/$', views.remove_drug, name='remove_drug'),
    url(r'^drug/update/(?P<drug_id>[0-9]+)/$', views.update_drug, name='update_drug'),
    url(r'^patient/$', views.view_patients, name='view_patients'),
    url(r'^patient_admin/$', views.view_patients_admin, name='view_patients_admin'),
    url(r'^patient/(?P<patient_id>[0-9]+)/$', views.view_medical_information, name='view_medical_information'),
    url(r'^diagnosis/create/(?P<patient_id>[0-9]+)/$', views.create_diagnosis, name='create_diagnosis'),
    url(r'^diagnosis/update/(?P<diagnosis_id>[0-9]+)/$', views.update_diagnosis, name='update_diagnosis'),
    url(r'^diagnosis/archive/(?P<diagnosis_id>[0-9]+)/$', views.archive_diagnosis, name='archive_diagnosis'),
    url(r'^prescriptions/(?P<patient_id>[0-9]+)/$', views.view_prescriptions, name='view_prescriptions'),
    url(r'^prescriptions/add/(?P<diagnosis_id>[0-9]+)/$', views.add_prescription, name='add_prescriptions'),
    url(r'^prescriptions/edit/(?P<prescription_id>[0-9]+)/$', views.edit_prescription, name='edit_prescriptions'),
    url(r'^prescriptions/remove/(?P<prescription_id>[0-9]+)/$', views.remove_prescription, name='remove_prescription'),
    url(r'^test/request/(?P<diagnosis_id>[0-9]+)/$', views.request_test, name='request_test'),
    url(r'^test/upload/(?P<test_id>[0-9]+)/$', views.upload_test_result, name='upload_test_result'),
    url(r'^test/test_view/$', views.test_view, name='test_view'),
    url(r'^test/release/(?P<test_id>[0-9]+)/$', views.release_test_result, name='release_test_result'),
    url(r'^test/test_detail/(?P<test_id>[0-9]+)/$', views.test_detail, name='test_detail'),
    url(r'^download_info/$', views.export_information, name='export_information'),
    url(r'^medical_info/$', views.medical_view_options, name='medical_info'),
    url(r'^medical_overview/$', views.medical_overview, name='medical_overview')
]

medical/models.py
from django.db import models
from datetime import date, timedelta
from hospital.models import Hospital, TreatmentSession
from account.models import Doctor, Patient
from .validator import validate_file_extension
import os


class Diagnosis(models.Model):
    treatment_session = models.ForeignKey(TreatmentSession, on_delete=models.CASCADE, null=True)

    patient = models.ForeignKey(Patient, on_delete=models.PROTECT, null=True)
    """A high level summary of this patient's condition, including any useful, medical information for the treatment"""
    summary = models.TextField()
    creation_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    archived = models.BooleanField(default=False)

    def get_patient(self):
        if self.patient:
            return self.patient

        return self.treatment_session.patient

    def __str__(self):
        if self.summary:
            line = self.summary.split('\n')[0]
            if len(line) < 97:
                return line
            else:
                return line[:97] + '...'
        else:
            return "Diagnosis created at %s" % self.creation_timestamp.ctime()

    class Meta:
        permissions = (
            ('view_diagnosis', 'Can view diagnoses'),
            ('view_own_diagnoses', 'Can view own diagnoses')
        )


class Test(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.PROTECT)
    diagnosis = models.ForeignKey(Diagnosis, on_delete=models.PROTECT)

    description = models.TextField()
    results = models.TextField()

    def content_file_name(self, filename):
        """
        Used to rename the file to pk of the doctor and test
        gives a unique name for each file
        :param filename: original filename
        :return: new filename
        """
        ext = filename.split('.')[-1]
        filename = "%s_%s.%s" % (self.doctor.id, self.id, ext)
        return os.path.join('medical/static/test_results', filename)

    file = models.FileField(default=None, upload_to=content_file_name, validators=[validate_file_extension])

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    uploaded = models.BooleanField(default=False)
    released = models.BooleanField(default=False)

    def status(self):
        if self.released:
            return 'released'
        elif self.uploaded:
            return 'uploaded'
        else:
            return 'pending'

    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        line = self.description.split('\n')[0]
        if len(line) < 77:
            return line
        else:
            return line[:77] + '...'

    class Meta:
        permissions = (
            ('request_test', 'Can request tests'),
            ('upload_test_results', 'Can upload test results'),
            ('release_test_results', 'Can release test results'),
            ('view_test_results', 'Can view tests'),
        )


class Drug(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()

    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ('remove_drug', 'Can remove drugs'),
            ('view_drug', 'Can view drugs'),
        )


class Prescription(models.Model):
    """
    Prescription class that has a diagnosis, doctor, drug, instructions for use
    which a prescribing doctor will create
    """
    diagnosis = models.ForeignKey(Diagnosis, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.PROTECT)
    drug = models.ForeignKey(Drug, on_delete=models.PROTECT)
    instruction = models.TextField()
    amount = models.IntegerField(default=1)
    cycle = models.IntegerField(null=True, blank=True, default=None)
    repeats = models.IntegerField(null=True, blank=True, default=None)
    creation_timestamp = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def pluralize_with_abbreviation(factor, unit):
        if factor == 1:
            return unit
        else:
            return '%d %ss' % (factor, unit)

    @staticmethod
    def pluralize(factor, unit):
        return ('%d %s' if factor == 1 else '%d %ss') % (factor, unit)

    def amount_str(self):
        return self.pluralize(self.amount, 'unit')

    def cycle_str(self):
        if not self.cycle:
            return 'N/A'

        if self.cycle % 30 == 0:
            return '%s (%s)' % (self.pluralize_with_abbreviation(self.cycle // 30, 'month'),
                                self.pluralize_with_abbreviation(self.cycle, 'day'))
        elif self.cycle % 7 == 0:
            return self.pluralize_with_abbreviation(self.cycle // 7, 'week')
        else:
            return self.pluralize_with_abbreviation(self.cycle, 'day')

    def quantity_info(self):
        if self.cycle:
            return '%s (refill every %s for %s)' % (self.amount_str(), self.cycle_str(), self.repeats_str())
        else:
            return '%s (one time)' % self.amount_str()

    def repeats_str(self):
        return self.pluralize(self.repeats, 'time')

    def expiration_date(self):
        return self.creation_timestamp.date() + timedelta(days=self.cycle)

    def active(self):
        return date.today() <= self.expiration_date()

    class Meta:
        permissions = (
            ('view_prescription', 'Can view prescriptions'),
            ('export_information', 'Can export information'),
        )

medical/forms.py
from django import forms
from .models import Drug, Diagnosis, Test, Prescription
from account.models import Patient


class DrugForm(forms.ModelForm):
    """
    A form for obtaining information related to a drug.
    Can be used for adding new drugs as well as editing existing drugs.
    """

    class Meta:
        model = Drug
        fields = ['name', 'description']


class DiagnosisForm(forms.ModelForm):
    def save_for_patient(self, patient):
        diagnosis = self.save(commit=False)

        diagnosis.patient = patient

        treatment_session = patient.get_current_treatment_session()
        if treatment_session:
            diagnosis.treatment_session = treatment_session
        else:
            pass

        diagnosis.save()

        return diagnosis

    class Meta:
        model = Diagnosis
        fields = ['summary']


class TestForm(forms.ModelForm):
    """
    A form for obtaining information for a medical test.
    """

    def save_for_diagnosis(self, doctor, diagnosis):
        test = self.save(commit=False)
        test.doctor = doctor
        test.diagnosis = diagnosis
        test.save()

        return test

    class Meta:
        model = Test
        fields = ['description']


class TestResultsForm(forms.ModelForm):
    """
    A form for obtaining test results in text form.
    """

    def uploadfile(self, file, commit=True):
        test = super(TestResultsForm, self).save(commit=commit)
        test.file = file
        test.uploaded = True
        test.save()

    def save(self, commit=True):
        test = super(TestResultsForm, self).save(commit=commit)
        test.uploaded = True
        test.save()

        return test

    class Meta:
        model = Test
        fields = ['results', 'file']


class PrescriptionForm(forms.ModelForm):
    def save_to_diagnosis_by_doctor(self, diagnosis, doctor, commit=True):
        prescription = super(PrescriptionForm, self).save(commit=False)
        prescription.diagnosis = diagnosis
        prescription.doctor = doctor

        if commit:
            prescription.save()

        return prescription

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if amount is not None and amount <= 0:
            raise forms.ValidationError('Cannot prescribe 0 or less units of drugs.')

        return amount

    def clean_cycle(self):
        cycle = self.cleaned_data.get('cycle')
        if cycle is not None and cycle <= 0:
            raise forms.ValidationError('Invalid value. Cycle duration must be greater than 0.')

        return cycle

    def clean_repeats(self):
        repeats = self.cleaned_data.get('repeats')
        if repeats is not None and repeats <= 0:
            raise forms.ValidationError('Invalid value. Repeat count must be greater than 0.')

        return repeats

    def clean(self):
        cleaned_data = super(PrescriptionForm, self).clean()
        repeats = self.cleaned_data.get('repeats')
        cycle = self.cleaned_data.get('cycle')

        if (repeats is None) != (cycle is None):
            raise forms.ValidationError('Cycle and repeats must be given at the same time.')

        return cleaned_data

    class Meta:
        model = Prescription
        fields = ['drug', 'instruction', 'amount', 'cycle', 'repeats']

medical/templates/medical/diagnosis/already_archived.html
{% extends 'index/base.html' %}
{% block title %}Archive Diagnosis{% endblock %}
{% block header %}Archive Diagnosis{% endblock %}
{% block content %}

    <div class="maincontent">
        <div class="whitebox" style="text-align:center;">
            <p>Diagnosis already archived.</p>
            <a href="{% url 'medical:update_diagnosis' diagnosis.id %}" class="btn btn-default btn-lg inactive">
                Back to Diagnosis
            </a>
        </div>
    </div>

{% endblock %}

medical/templates/medical/diagnosis/archive.html
{% extends 'index/base.html' %}
{% block title %}Archive Diagnosis{% endblock %}
{% block header %}Archive Diagnosis{% endblock %}

{% block content %}
<div class="maincontent">
    <div class="whitebox">
        <h1>Warning: This Action is Permanent</h1>
        <p>
            Are you sure you want to archive this diagnosis? It will still be displayed for the patient, but set
            as inactive.
        </p>
        <form method="post">
            {% csrf_token %}
            <div class="parentbutton">
                <div class="leftbutton">
                    <input type="hidden" name="post" value="yes"/>
                    <input type="submit" value="Archive" class="btn btn-default btn-lg inactive"/>
                </div>
                <div class="rightbutton">
                    <a href="{% url 'medical:update_diagnosis' diagnosis.id %}"
                       class="btn btn-default btn-lg inactive" role="button">Back to Diagnosis</a>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

medical/templates/medical/diagnosis/archive_done.html
{% extends 'index/base.html' %}
{% block title %}Archive Diagnosis{% endblock %}
{% block header %}Archive Diagnosis{% endblock %}
{% block content %}

    <div class="maincontent">
        <div class="whitebox" style="text-align:center;">
            <p>Diagnosis archived.</p>
            <a href="{% url 'medical:update_diagnosis' diagnosis.id %}" class="btn btn-default btn-lg inactive">
                Back to Diagnosis
            </a>
        </div>
    </div>

{% endblock %}

medical/templates/medical/diagnosis/create.html
{% extends 'index/base.html' %}
{% block title %}Create Diagnosis{% endblock %}
{% block header %}Create Diagnosis{% endblock %}

{% block content %}
    <div class="maincontent">
        <div class="whitebox">
            <h3 style="text-align: center">
                New diagnosis for {{ patient.user.first_name }} {{ patient.user.last_name }}
            </h3>

            <form method="post" action="{% url 'medical:create_diagnosis' patient.id %}">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>

                <div class="parentbutton">
                    <div class="leftbutton">
                        <input type="submit" value="Add" class="btn btn-default btn-lg inactive"/>
                    </div>
                    <div class="rightbutton">
                        <a href="#" onclick="window.history.back(); return false;"
                           class="btn btn-default btn-lg inactive" role="button">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

medical/templates/medical/diagnosis/update.html
{% extends 'index/base.html' %}
{% block title %}Update Diagnosis{% endblock %}
{% block header %}Update Diagnosis{% endblock %}

{% block content %}
<div class="maincontent">
    <div class="whitebox">
        <h3 style="text-align: center">
            Diagnosis for {{ form.instance.get_patient.user.first_name }} {{ form.instance.patient.user.last_name }}
        </h3>

        {% if archived %}
        <p style="text-align: center; color: red">
            Archived
        </p>
        {% else %}
        <div class="parentbutton">
            <div class="rightbutton">
                <a href="{% url 'medical:archive_diagnosis' form.instance.id %}"
                   class="btn btn-default btn-lg inactive" role="button">Archive</a>
            </div>
        </div>
        <div class=col-xs-12" style="height:40px;"></div>
        {% endif %}

        {% if message %}
        <p style="text-align: center;">{{ message }}</p>
        {% endif %}

        <form method="post" action="{% url 'medical:update_diagnosis' form.instance.id %}"
              style="margin-bottom: 44pt;">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>

            <div class="parentbutton">
                <div class="leftbutton">
                    <input type="submit" value="Save" class="btn btn-default btn-lg inactive"/>
                </div>
                <div class="rightbutton">
                    <a href="{% url 'medical:view_medical_information' form.instance.patient.id %}"
                       class="btn btn-default btn-lg inactive" role="button">Back to Patient</a>
                </div>
            </div>
        </form>

        <div style="text-align: center;">
            <h3 style="text-align: center;">Tests</h3>

            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <td class="lead" style="font-weight: bold;">Description</td>
                    <td class="lead" style="font-weight: bold;">Status</td>
                    <td></td>
                </tr>
                </thead>
                <tbody>
                {% for test in form.instance.test_set.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{% url 'medical:upload_test_result' test.id %}">{{ test }}</a></td>
                    <td>{{ test.status }}</td>
                    <td>
                        {% if test.uploaded and not test.released %}
                        <a href="{% url 'medical:release_test_result' test.id %}"
                           class="btn btn-success btn-xs">Publish</a>
                        {% else %}
                        <a href="#" class="btn btn-success btn-xs disabled" disabled>Publish</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <a href="{% url 'medical:request_test' form.instance.id %}" class="btn btn-primary btn-lg">Request Test</a>
        </div>

        <div style="text-align: center;">
            <h3 style="text-align: center;">Prescriptions</h3>

            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <td class="lead" style="font-weight: bold;">Drug</td>
                    <td class="lead" style="font-weight: bold;">Prescribing Doctor</td>
                    <td class="lead" style="font-weight: bold;">Quantity Info</td>
                </tr>
                </thead>
                <tbody>
                {% for prescription in form.instance.prescription_set.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        <a href="{% url 'medical:edit_prescriptions' prescription.id %}">{{ prescription.drug }}</a>
                    </td>
                    <td>{{ prescription.doctor.full_name }}</td>
                    <td>{{ prescription.quantity_info }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <a href="{% url 'medical:add_prescriptions' form.instance.id %}" class="btn btn-primary btn-lg">Add
                Prescription</a>
        </div>

    </div>
</div>

{% endblock %}