account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'account'
urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'account/common/login.html', 'authentication_form': forms.UserAuthenticationForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'account/common/logout.html'}, name='logout'),
    url(r'^patient/register/$', views.register_patient, name='register_patient'),
    url(r'^administrator/create/$', views.create_administrator, name='create_administrator'),
    url(r'^doctor/create/$', views.register_doctor, name='create_doctor'),
    url(r'^nurse/create/$', views.create_nurse, name='create_nurse'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^add/$', views.add_account, name='add_account'),
]

hnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('index.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^reservation/', include('reservation.urls')),
    url(r'^hospital/', include('hospital.urls')),
    url(r'^medical/', include('medical.urls')),
    url(r'^messaging/', include('messaging.urls')),
]

index/urls.py
from django.conf.urls import url
from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^patient/$', views.patient, name='patient'),
    url(r'^doctor/$', views.doctor, name='doctor'),
    url(r'^nurse/$', views.nurse, name='nurse'),
    url(r'^administrator/$', views.administrator, name='administrator'),
    url(r'^administrator/log/$', views.log, name='log'),
    url(r'^administrator/log/activity.log$', views.log, name='log'),
    url(r'^system_administrator/$', views.system_administrator, name='system_administrator'),
    url(r'^stephen$', views.stephen, name='stephen'),
]

messaging/urls.py
from django.conf.urls import url
from . import views

app_name = 'messaging'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^send/$', views.send_message, name='send'),
    url(r'^inbox/$', views.view_received_messages, name='inbox'),
    url(r'^outbox/$', views.view_sent_messages, name='outbox'),
]

messaging/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    """
    Message model has a sender and recipient which will be the username of a recipient
    Each message has a timestamp when it is sent and the message text
    """
    sender = models.ForeignKey(User, on_delete=models.PROTECT, related_name='sent_messages')
    recipient = models.ForeignKey(User, on_delete=models.PROTECT, related_name='received_messages')

    content = models.TextField()

    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

messaging/forms.py
from django import forms
from .models import Message
from django.contrib.auth.models import User


class MessageForm(forms.ModelForm):
    sender = None

    recipient_username = forms.CharField(
        label='Recipient',
        help_text='The username of the recipient.',
        required=True
    )

    def clean_recipient_username(self):
        recipient_username = self.cleaned_data.get('recipient_username')
        if recipient_username:
            try:
                recipient = User.objects.get(username=recipient_username)
                if recipient == self.sender:
                    raise forms.ValidationError("The recipient cannot be yourself. "
                                                "We just, you know, don't like that.")
                return recipient
            except User.DoesNotExist:
                raise forms.ValidationError('User with this username does not exist.')

    def save(self, commit=False):
        message = super(MessageForm, self).save(commit=False)
        message.sender = self.sender
        message.recipient = self.cleaned_data['recipient_username']
        message.save()

        return message

    class Meta:
        model = Message
        fields = ['recipient_username', 'content']

messaging/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Message
from .forms import MessageForm


@login_required
def index(request):
    return render(request, 'messaging/index.html')


@login_required
def send_message(request):
    """ Send a message from one user to another through the use of the form"""
    if request.method == 'POST':
        form = MessageForm(request.POST)
        form.sender = request.user
        if form.is_valid():
            form.save()
            return render(request, 'messaging/index.html')
    else:
        form = MessageForm()

    return render(request, 'messaging/send.html', {'form': form})


@login_required
def view_received_messages(request):
    """"Get all the messages corresponding to the user"""
    messages = Message.objects.filter(recipient=request.user)
    return render(request, 'messaging/inbox.html', {'message_list': messages})


@login_required
def view_sent_messages(request):
    """ filter and view all sent messages from a given user"""
    messages = Message.objects.filter(sender=request.user)
    return render(request, 'messaging/outbox.html', {'message_list': messages})

messaging/templates/messaging/inbox.html
{% extends 'index/base.html' %}
{% block title %}Messages{% endblock %}
{% block header %}Your Messages{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-8 col-md-offset-2">
            <div id="jumbo" class="jumbotron">
                <h2 style="text-align:center;">Your Message Inbox</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Sender</th>
                        <th>Message</th>
                        <th>Time</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for message in message_list %}
                        <tr>
                            <td>{{ message.sender }}</td>
                            <td>{{ message.content }}</td>
                            <td>{{ message.timestamp }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a class="button" href="{% url 'messaging:index' %}">Back</a>
            </div>
        </div>
    </div>

{% endblock %}

messaging/templates/messaging/index.html
{% extends 'index/base.html' %}
{% block title %}Dashboard{% endblock %}
{% block header %}Doctor Dashboard {% endblock %}
{% block login %}
    <li><a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
{% endblock %}
{% block content %}

    <div class="container" role="main">
        <div class="hyper">
            <div id="jumbo" class="jumbotron">
                <h1>HNet Messaging System</h1>
                <p>From here, you can send and receive messages to other users of this system.</p>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <a target="_parent" href="{% url 'messaging:send' %}">
                        <button class="iconbutton">
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                            <p style="font-size:20px;">Send Message</p>
                        </button>
                    </a>
                </div>

                <div class="col-md-4">
                    <a target="_parent" href="{% url 'messaging:inbox' %}">
                        <button class="iconbutton">
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                            <p style="font-size:20px;">Message Inbox</p>
                        </button>
                    </a>
                </div>

                <div class="col-md-4">
                    <a target="_parent" href="{% url 'messaging:outbox' %}">
                        <button class="iconbutton">
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                            <p style="font-size:20px;">Message Outbox</p>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

messaging/templates/messaging/outbox.html
{% extends 'index/base.html' %}
{% block title %}Message Outbox{% endblock %}
{% block header %}Your Message Outbox{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-8 col-md-offset-2">
            <div id="jumbo" class="jumbotron">
                <h2 style="text-align:center;">Your Message Outbox</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Recipient</th>
                        <th>Message</th>
                        <th>Time</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for message in message_list %}
                        <tr>
                            <td>{{ message.recipient }}</td>
                            <td>{{ message.content }}</td>
                            <td>{{ message.timestamp }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a class="button" href="{% url 'messaging:index' %}">Back</a>
            </div>
        </div>
    </div>

{% endblock %}

messaging/templates/messaging/send.html
{% extends 'index/base.html' %}
{% block title %}New Message{% endblock %}
{% block header %}Drafting New Message{% endblock %}

{% block content %}
    <div class="maincontent">
        <div class="whitebox_small">
            <form method="post" action="{% url 'messaging:send' %}">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <div class="parentbutton">
                    <div class="leftbutton">
                        <input type="submit" value="Send" class="button"/>
                    </div>
                    <div class="rightbutton">
                        <a href="#" onclick="window.history.back(); return false;">
                            <button class="button">Back</button>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

messaging/templates/messaging/send_done.html
Message sent.<br/>
This page is only a placeholder.<br/>
Replace the link to this page with the link to the message list after it's implemented.<br/>
<a href="{% url 'index:index' %}">Back to dashboard</a>